---
title: "USVI Coral Sampling Data Exploration"
author: "Emily Sesno"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 6
    toc_float: yes
  pdf_document:
    keep_tex: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
rm(list=ls(all=TRUE))

results <- read.csv("Data/Genotype_Samples_2022.csv", header=T, na.strings="NA")

library("plyr") 
library("dplyr")
library("tidyverse")
library("knitr")
library("tidyr")
library("janitor") #allows to group by Location (group_by wasn't working properly)

library("DT") #used to create html file with color coded species counts
library("webshot")

#TotalCount22 <-
  #results %>% 
  #drop_na(Species) %>% 
  #count(Species)

```

# Species Counts by Location
## St. Thomas
```{r data explore STT, echo=FALSE}

spcountSTT <- 
  results %>% 
  select("VialID", "Species", "Island") %>% 
  filter(Island %in% c("STT", "CWORI Nursery")) %>% 
  separate(col=VialID, into=c('Location', 'SampNum'), sep='_') %>% 
  drop_na(Species) %>% 
  tabyl(Species, Location) 
  
spcountColorSTT <-
  spcount %>% 
  datatable(head(spcount), class = 'cell-border stripe hover compact') %>%
  formatStyle('Species', fontWeight = 'bold') %>% 
  formatStyle('BLP', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BUK', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')),
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('COK', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green', 'green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('FLR', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('IBR', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('MEG', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('SAP', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('SEA', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('UVI', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
                fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('THC', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
                fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('COW', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
                fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('MER', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
                fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BOT', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
                fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('CNU', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
                fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('GSJ', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
                fontWeight = styleInterval(14, c('normal', 'bold')))
  


saveWidget(spcountColorSTT, "Documents/spcounttable.html_StThomas") #would love to figure out a different way to save so we don't have all the excess html stuff...
  

```


## St. Croix
###St. Croix 2022 only
```{r data explore STX, echo=FALSE}

spcountSTX <- 
  results %>% 
  select("VialID", "Species", "Island") %>% 
  filter(Island == "STX") %>% 
  separate(col=VialID, into=c('Location', 'SampNum'), sep='_') %>% 
  drop_na(Species) %>% 
  tabyl(Species, Location) 
  
spcountColorSTX <-
  spcountSTX %>% 
  datatable(head(spcountSTX), class = 'cell-border stripe hover compact') %>%
  formatStyle('Species', fontWeight = 'bold') %>% 
  formatStyle('SRA', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BIA', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BIB', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BIC', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BID', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BUT', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('SRB', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('CBE', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('SRC', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('BIZ', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('TBW', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('THO', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('DEB', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('FRD', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) 

saveWidget(spcountColorSTX, "Documents/spcounttable_StCroix.html") #would love to figure out a different way to save so we don't have all the excess html stuff...
  

```

## STX combine 2021 and 2022
```{r data explore STX21and22, echo=FALSE}

results21 <- read.csv("Data/Genotype_Samples_2021.csv", header=T, na.strings="NA")

spcountSTX21 <- 
  results21 %>% 
  select("VialID", "Species", "Location") %>% 
  separate(col=VialID, into=c('Island', 'SampNum'), sep='_') %>% 
  filter(Island == "STX") %>% 
  drop_na(Species) %>% 
  tabyl(Species, Location) 

STXcounts <-
  full_join(spcountSTX, spcountSTX21, by="Species", copy=TRUE) %>%
  mutate_all(~replace(., is.na(.), 0)) %>% #replace NAs in ACER with 0
  mutate(BIE = BIA + BIB, BIA = NULL, BIB = NULL) %>% 
  mutate(BINE = BUIS4 + BUIS5 + BUIS2 + BUIS3, BUIS4=NULL, BUIS5=NULL, BUIS2=NULL, BUIS3=NULL) %>% 
  mutate(BISE = BIC + BUIS1, BIC = NULL, BUIS1 = NULL) %>% 
  dplyr::rename(BINW=BID) %>% 
  select("Species", "BIE","BINE", "BINW", "BISE", "BUT","CBE", "SRA", "SRB", "SRC", "BIZ", "TBW", "THO", "DEB", "FRD")

STXallcountsColor <-
  STXcounts %>% 
  datatable(head(STXcounts), class = 'cell-border stripe hover compact') %>%
  formatStyle('Species', fontWeight = 'bold') %>% 
  formatStyle('BINW', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('BUT', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('SRA', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('SRB', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('BIE', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('BINE', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('BISE', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>%
    formatStyle('CBE', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('SRC', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('BIZ', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
    formatStyle('TBW', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('THO', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('DEB', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold'))) %>% 
  formatStyle('FRD', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')), 
              fontWeight = styleInterval(14, c('normal', 'bold')))

saveWidget(STXallcountsColor, "Documents/spcounttable_StCroixTotal.html") 



```

## STJ combine 2021 and 2022
```{r data explore STX21and22, echo=FALSE}

results21 <- read.csv("Data/Genotype_Samples_2021.csv", header=T, na.strings="NA")

spcountSTJ21 <- 
  results21 %>% 
  select("VialID", "Species", "Location") %>% 
  separate(col=VialID, into=c('Island', 'SampNum'), sep='_') %>% 
  filter(Island == "STJ") %>% 
  drop_na(Species) %>% 
  tabyl(Species, Location) 

spcountSTJ22 <- 
  results %>% 
  select("VialID", "Species", "Island") %>% 
  filter(Island == "STJ") %>% 
  separate(col=VialID, into=c('Location', 'SampNum'), sep='_') %>% 
  drop_na(Species) %>% 
  tabyl(Species, Location)

STJcounts <-
  full_join(spcountSTJ22, spcountSTJ21, by="Species", copy=TRUE) %>%
  mutate_all(~replace(., is.na(.), 0)) %>% #replace NAs in ACER with 0
  
STJcountsColor <- 
  spcountSTJ22 %>% 
    datatable(head(STXcounts), class = 'cell-border stripe hover compact') %>%
    formatStyle('Species', fontWeight = 'bold') %>% 
    formatStyle('LEI', 
                color = styleInterval(c(11, 14, 15), 
                                      c('red', 'purple', 'green','green'))) %>% 
    formatStyle('HNB', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green'))) %>% 
    formatStyle('TEK', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green'))) %>% 
    formatStyle('YAW', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green'))) %>% 
    formatStyle('JON', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')))
  
STJallcountsColor <-
  STJcounts %>% 
  datatable(head(STJcounts), class = 'cell-border stripe hover compact') %>%
  formatStyle('Species', fontWeight = 'bold') %>% 
  formatStyle('LEI', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green'))) %>%
  formatStyle('HNB', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green'))) %>% 
  formatStyle('TEK', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green'))) %>% 
  formatStyle('YAW', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green'))) %>% 
  formatStyle('JON', 
              color = styleInterval(c(11, 14, 15), 
                                    c('red', 'purple', 'green','green')))
  
```

# GPS Data Exploration and Point Matching
```{r GPS data explore}

#create new data frame gpsUpdate that accurately represents the time for correct time zone. Will use this to autofind corresponding times in our metadata sheet

#read csv, change file name to the file that matches the day you are exploring
gps <- read.csv("Data/GPS Data/GPS_LEI_5Jul2022.csv", header=T, na.strings="NA", stringsAsFactors=FALSE)

gpsUpdate <- 
  gps %>% 
  #Select relevant variables
    select("lat", "lon", "time") %>% 
  #adjust time column to have all common separators 
    mutate(time=str_replace_all(time,"[:punct:]","-")) %>% 
  #separate the time column to have Date and times
    separate(col=time, into=c('Year', 'Month', "DayHour", "Min","Sec"),
             sep='-') %>% 
  #separate further to account for a random T in GPS data  
    separate(col=DayHour, into=c('Day', 'Hour'), sep='T') %>% 
  #Select for relevent varaibles, remove the Z in seconds, reselect variables
    select("Year","Month","Day","Hour","Min", "lat","lon") %>%
    #mutate(Month = sprintf("%02d", as.numeric(Month))) %>% 
  #recombine the date column into one   
    unite(col="Date", c("Month","Day","Year",), sep = "/") %>% 
  #make hour column numeric from character (not sure why it saw it as character) and ensure the seconds are 01, 02 etc.
    mutate(Hour = as.numeric(Hour), Min= sprintf("%02d", as.numeric(Min))) %>%
  #add a column to adjust for time change issues
    mutate(Hour=Hour-4) %>% #only do this if the time is wrong, from earlier days
  #recombine the hour and min of time to be one column
    unite(col="Time", c("Hour","Min"), sep=':') %>% 
  #create nuew column that establishes the date as a proper date format, not sure if necessary?
    #mutate(Date=strptime(Date, format = "%Y-%m-%d")) 
  #Remove duplicate times
  distinct(Time, .keep_all=TRUE)

resultsforgps <-
  results %>% 
    select("Date","VialID", "Tag..", "Time.Collected") %>% 
    rename(Time=Time.Collected)

gpsMatched <-
  inner_join(resultsforgps, gpsUpdate, by = c("Date","Time")) #inner join to only keep the matched values

#Save CSV file, change name to match date explored
write.csv(gpsMatched,"Data/GPS Data/GPS_LEI_5Jul2022_matched2.csv", row.names = TRUE)

    
```


