
#Setup and load packages
```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
rm(list=ls(all=TRUE))

results <- read.csv("Data/Genotype_Samples_2022.csv", header=T, na.strings="NA")

library("plyr") 
library("dplyr")
library("tidyverse")
library("knitr")
library("tidyr")
library("janitor") #allows to group by Location (group_by wasn't working properly)

```

# GPS Data Exploration and Point Matching
```{r GPS data explore}

#create new data frame gpsUpdate that accurately represents the time for correct time zone. Will use this to autofind corresponding times in our metadata sheet

#read csv, change file name to the file that matches the day you are exploring
gps <- read.csv("Data/GPS Data/GPS_STV_4Aug2022.csv", header=T, na.strings="NA", stringsAsFactors=FALSE)

gpsUpdate <- 
  gps %>% 
  #Select relevant variables
    select("lat", "lon", "time") %>% 
  #adjust time column to have all common separators 
    mutate(time=str_replace_all(time,"[:punct:]","-")) %>% 
  #separate the time column to have Date and times
    separate(col=time, into=c('Year', 'Month', "DayHour", "Min","Sec"),
             sep='-') %>% 
  #separate further to account for a random T in GPS data  
    separate(col=DayHour, into=c('Day', 'Hour'), sep='T') %>% 
  #Select for relevent varaibles, remove the Z in seconds, reselect variables
    select("Year","Month","Day","Hour","Min", "lat","lon") %>%
    #mutate(Month = sprintf("%02d", as.numeric(Month))) %>% 
  #recombine the date column into one   
    unite(col="Date", c("Month","Day","Year",), sep = "/") %>% 
  #make hour column numeric from character (not sure why it saw it as character) and ensure the seconds are 01, 02 etc.
    mutate(Hour = as.numeric(Hour), Min= sprintf("%02d", as.numeric(Min))) %>%
  #add a column to adjust for time change issues
    mutate(Hour=Hour-4) %>% #only do this if the time is wrong, from earlier days
  #recombine the hour and min of time to be one column
    unite(col="Time", c("Hour","Min"), sep=':') %>% 
  #create nuew column that establishes the date as a proper date format, not sure if necessary?
    #mutate(Date=strptime(Date, format = "%Y-%m-%d")) %>% 
  #Remove duplicate times
  distinct(Time, .keep_all=TRUE)

resultsforgps <-
  results %>% 
    select("Date","VialID", "Tag..", "Time.Collected") %>% 
    dplyr::rename(Time=Time.Collected) %>%
    separate(col=Date, into=c('Month','Day','Year'), sep='/') %>% 
    mutate(Month = sprintf("%02d", as.numeric(Month)),
           Day = sprintf("%02d", as.numeric(Day))) %>% 
    unite(col="Date", c("Month","Day","Year",), sep = "/")

gpsMatched <-
  inner_join(resultsforgps, gpsUpdate, by = c("Date","Time")) #inner join to only keep the matched values

#Save CSV file, change name to match date explored
write.csv(gpsMatched,"Data/GPS Data/GPS_STV_4Aug2022_matched2.csv", row.names = TRUE)

    
```